services:
  - type: web
    name: my-proxy-checker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
